import React, { createContext, useContext, useState, ReactNode } from 'react';

// --- Supported Languages ---
export const languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
];

type LanguageContextType = {
  currentLanguage: typeof languages[0];
  setLanguage: (code: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// --- MASTER DICTIONARY (Dashboard + Issue + Verify + Dropdowns) ---
const translations: Record<string, Record<string, string>> = {
  en: {
    // --- Navbar & Dashboard ---
    dashboard: "Dashboard", issue: "Issue", verify: "Verify", myCerts: "My Certificates", connect: "Connect Wallet", disconnect: "Disconnect",
    heroTitle: "Digital Trust,", heroSubtitle: "Simplified.", heroDesc: "OpenCred brings clarity to certification. Secure, tamper-proof, and built for the future.",
    issueTitle: "Issue Certificates", issueDesc: "Deploy blockchain-verified credentials directly to recipients.",
    verifyTitle: "Verify Authenticity", verifyDesc: "Instantly validate any certificate using our decentralized ledger.",
    walletTitle: "Digital Wallet", walletDesc: "Securely manage your professional achievements in one place.",

    // --- Issue Page ---
    iss_pageTitle: "Issue Credentials", iss_pageSubtitle: "Deploy immutable records to the blockchain.", iss_guideBtn: "Read User Guide",
    iss_single: "Single", iss_bulk: "Bulk Upload", iss_step1: "Classification", iss_step2: "Recipient", iss_step3: "Details",
    iss_cat: "Category", iss_subcat: "Subcategory", iss_temp: "Template", iss_name: "Full Legal Name", iss_wallet: "Wallet Address",
    iss_date: "Issue Date", iss_btn: "Issue Certificate", iss_btn_processing: "Processing...", iss_bulk_drop: "Drop Excel File", iss_bulk_btn: "Start Bulk Issue",
    iss_select_cat: "Select a classification to view details", iss_event: "Event Name",
    lbl_course: "Course Name", lbl_org: "Organization", lbl_grade: "Grade / GPA", lbl_ref: "Reference ID", lbl_achievements: "Achievements",
    cat_academic: "Academic Credentials", cat_skill: "Skill & Training", cat_employment: "Employment Record", cat_gov: "Government ID", cat_gig: "Gig Work",

    // --- Verify Page ---
    ver_immutable: "Immutable",
    ver_pageTitle: "Verify Authenticity.",
    ver_pageSubtitle: "Instant, trustless verification. Enter a unique ID to validate the integrity of any OpenCred certificate.",
    ver_placeholder: "Paste Certificate ID (e.g. d2cfe4d4...)",
    ver_btn: "Verify",
    ver_scanning: "Scanning...",
    ver_step1_title: "Locate ID",
    ver_step1_desc: "Find the UUID at the bottom of your certificate or link.",
    ver_step2_title: "Input & Search",
    ver_step2_desc: "System queries the blockchain ledger instantly.",
    ver_step3_title: "Validate",
    ver_step3_desc: "View cryptographic proofs and signatures.",
    ver_res_back: "Back to Search",
    ver_res_title: "Verification Result",
    ver_res_auth: "Authentic Document",
    ver_res_inv: "Invalid Document",
    ver_res_rec: "Recipient",
    ver_res_date: "Issue Date",
    ver_res_type: "Type",
    ver_view_chain: "View on Chain",

    // --- Dropdown Options (Subcategories & Types) ---
    "Degree Certificate": "Degree Certificate",
    "Diploma Certificate": "Diploma Certificate",
    "Marksheet / Transcript": "Marksheet / Transcript",
    "Course Completion": "Course Completion",
    "Research Grant": "Research Grant",
    "Skill Certification": "Skill Certification",
    "Training Completion": "Training Completion",
    "Workshop / Bootcamp": "Workshop / Bootcamp",
    "Language Proficiency": "Language Proficiency",
    "Experience Letter": "Experience Letter",
    "Internship Certificate": "Internship Certificate",
    "Employment Verification": "Employment Verification",
    "Recommendation Letter": "Recommendation Letter",
    "Professional License": "Professional License",
    "Government Authorization": "Government Authorization",
    "Regulatory Certificate": "Regulatory Certificate",
    "Identity Proof": "Identity Proof",
    "Gig Work Record": "Gig Work Record",
    "Platform Skill Rating": "Platform Skill Rating",
    "Work History Summary": "Work History Summary",
    "Project Completion": "Project Completion",
    "Certificate of Completion": "Certificate of Completion",
    "Certificate of Achievement": "Certificate of Achievement",
    "Certificate of Participation": "Certificate of Participation",
    "Certificate of Excellence": "Certificate of Excellence",
    "Training Certificate": "Training Certificate",
    "Official License": "Official License",
    "Verification Letter": "Verification Letter"
  },
  hi: {
    dashboard: "डैशबोर्ड", issue: "जारी करें", verify: "सत्यापन", myCerts: "मेरे प्रमाणपत्र", connect: "वॉलेट कनेक्ट", disconnect: "डिस्कनेक्ट",
    heroTitle: "डिजिटल विश्वास,", heroSubtitle: "सरल बनाया गया।", heroDesc: "OpenCred प्रमाणन में स्पष्टता लाता है। सुरक्षित और छेड़छाड़-रोधी।",
    issueTitle: "प्रमाणपत्र जारी करें", issueDesc: "ब्लॉकचेन-सत्यापित क्रेडेंशियल्स सीधे भेजें।",
    verifyTitle: "प्रमाणिकता जांचें", verifyDesc: "हमारे बहीखाते का उपयोग करके तुरंत मान्य करें।",
    walletTitle: "डिजिटल वॉलेट", walletDesc: "अपनी उपलब्धियों को सुरक्षित रूप से प्रबंधित करें।",

    iss_pageTitle: "क्रेडेंशियल्स जारी करें", iss_pageSubtitle: "ब्लॉकचेन पर अमिट रिकॉर्ड तैनात करें।", iss_guideBtn: "गाइड पढ़ें",
    iss_single: "एकल", iss_bulk: "थोक अपलोड", iss_step1: "वर्गीकरण", iss_step2: "प्राप्तकर्ता", iss_step3: "विवरण",
    iss_cat: "श्रेणी", iss_subcat: "उप-श्रेणी", iss_temp: "टेम्पलेट", iss_name: "पूरा नाम", iss_wallet: "वॉलेट पता",
    iss_date: "जारी तिथि", iss_btn: "जारी करें", iss_btn_processing: "प्रक्रिया जारी...", iss_bulk_drop: "एक्सेल फ़ाइल डालें", iss_bulk_btn: "थोक जारी करें",
    iss_select_cat: "विवरण देखने के लिए श्रेणी चुनें", iss_event: "इवेंट नाम",
    lbl_course: "पाठ्यक्रम", lbl_org: "संगठन", lbl_grade: "ग्रेड", lbl_ref: "संदर्भ आईडी", lbl_achievements: "उपलब्धियाँ",
    cat_academic: "शैक्षणिक योग्यता", cat_skill: "कौशल प्रशिक्षण", cat_employment: "रोज़गार रिकॉर्ड", cat_gov: "सरकारी आईडी", cat_gig: "गिग कार्य",

    ver_immutable: "अपरिवर्तनीय",
    ver_pageTitle: "प्रमाणिकता की जाँच करें।",
    ver_pageSubtitle: "तत्काल, विश्वसनीय सत्यापन। किसी भी प्रमाणपत्र की अखंडता को मान्य करने के लिए आईडी दर्ज करें।",
    ver_placeholder: "प्रमाणपत्र आईडी पेस्ट करें (जैसे d2cfe4d4...)",
    ver_btn: "सत्यापित करें",
    ver_scanning: "स्कैनिंग...",
    ver_step1_title: "आईडी खोजें",
    ver_step1_desc: "अपने प्रमाणपत्र या लिंक के नीचे UUID खोजें।",
    ver_step2_title: "इनपुट और खोज",
    ver_step2_desc: "सिस्टम तुरंत ब्लॉकचेन बहीखाता को क्वेरी करता है।",
    ver_step3_title: "मान्य करें",
    ver_step3_desc: "क्रिप्टोग्राफिक प्रमाण और हस्ताक्षर देखें।",
    ver_res_back: "खोज पर वापस जाएं",
    ver_res_title: "सत्यापन परिणाम",
    ver_res_auth: "प्रामाणिक दस्तावेज",
    ver_res_inv: "अमान्य दस्तावेज",
    ver_res_rec: "प्राप्तकर्ता",
    ver_res_date: "जारी तिथि",
    ver_res_type: "प्रकार",
    ver_view_chain: "चेन पर देखें",

    // --- Dropdown Options ---
    "Degree Certificate": "डिग्री प्रमाण पत्र",
    "Diploma Certificate": "डिप्लोमा प्रमाण पत्र",
    "Marksheet / Transcript": "अंकपत्र / ट्रांसक्रिप्ट",
    "Course Completion": "कोर्स पूरा होने का प्रमाण",
    "Research Grant": "अनुसंधान अनुदान",
    "Skill Certification": "कौशल प्रमाणन",
    "Training Completion": "प्रशिक्षण पूर्णता",
    "Workshop / Bootcamp": "कार्यशाला / बूटकैम्प",
    "Language Proficiency": "भाषा प्रवीणता",
    "Experience Letter": "अनुभव पत्र",
    "Internship Certificate": "इंटर्नशिप प्रमाण पत्र",
    "Employment Verification": "रोज़गार सत्यापन",
    "Recommendation Letter": "सिफारिश पत्र",
    "Professional License": "वृतिक अनुज्ञाप्ति",
    "Government Authorization": "सरकारी प्राधिकरण",
    "Regulatory Certificate": "विनियामक प्रमाण पत्र",
    "Identity Proof": "पहचान प्रमाण",
    "Gig Work Record": "गिग कार्य रिकॉर्ड",
    "Platform Skill Rating": "प्लेटफ़ॉर्म कौशल रेटिंग",
    "Work History Summary": "कार्य इतिहास सारांश",
    "Project Completion": "परियोजना पूर्णता",
    "Certificate of Completion": "पूर्णता प्रमाण पत्र",
    "Certificate of Achievement": "उपलब्धि प्रमाण पत्र",
    "Certificate of Participation": "भागीदारी प्रमाण पत्र",
    "Certificate of Excellence": "उत्कृष्टता प्रमाण पत्र",
    "Training Certificate": "प्रशिक्षण प्रमाण पत्र",
    "Official License": "आधिकारिक लाइसेंस",
    "Verification Letter": "सत्यापन पत्र"
  },
  bn: {
    dashboard: "ড্যাশবোর্ড", issue: "ইস্যু", verify: "যাচাই", myCerts: "আমার সার্টিফিকেট", connect: "সংযুক্ত করুন", disconnect: "বিচ্ছিন্ন",
    heroTitle: "ডিজিটাল বিশ্বাস,", heroSubtitle: "সহজ করা হয়েছে।", heroDesc: "OpenCred সার্টিফিকেশনে স্বচ্ছতা নিয়ে আসে। নিরাপদ এবং টেম্পার-প্রুফ।",
    issueTitle: "সার্টিফিকেট দিন", issueDesc: "ব্লকচেইন-যাচাইকৃত প্রশংসাপত্র পাঠান।",
    verifyTitle: "সত্যতা যাচাই", verifyDesc: "যেকোনো সার্টিফিকেট তাৎক্ষণিকভাবে যাচাই করুন।",
    walletTitle: "ডিজিটাল ওয়ালেট", walletDesc: "আপনার অর্জনগুলো নিরাপদে রাখুন।",

    iss_pageTitle: "শংসাপত্র প্রদান", iss_pageSubtitle: "ব্লকচেইনে রেকর্ড স্থাপন করুন।", iss_guideBtn: "গাইড পড়ুন",
    iss_single: "একক", iss_bulk: "বাল্ক আপলোড", iss_step1: "শ্রেণিবিন্যাস", iss_step2: "প্রাপক", iss_step3: "বিবরণ",
    iss_cat: "বিভাগ", iss_subcat: "উপ-বিভাগ", iss_temp: "টেমপ্লেট", iss_name: "পুরো নাম", iss_wallet: "ওয়ালেট ঠিকানা",
    iss_date: "তারিখ", iss_btn: "ইস্যু করুন", iss_btn_processing: "প্রক্রিয়া চলছে...", iss_bulk_drop: "এক্সেল ফাইল দিন", iss_bulk_btn: "শুরু করুন",
    iss_select_cat: "বিবরণ দেখতে বিভাগ বাছুন", iss_event: "ইভেন্ট নাম",
    lbl_course: "কোর্স", lbl_org: "প্রতিষ্ঠান", lbl_grade: "গ্রেড", lbl_ref: "রেফারেন্স আইডি", lbl_achievements: "কৃতিত্ব",
    cat_academic: "একাডেমিক তথ্য", cat_skill: "দক্ষতা", cat_employment: "চাকরি", cat_gov: "সরকারি আইডি", cat_gig: "গিগ কাজ",

    ver_immutable: "অপরিবর্তনীয়",
    ver_pageTitle: "সত্যতা যাচাই করুন।",
    ver_pageSubtitle: "তাত্ক্ষণিক এবং নিরাপদ যাচাইকরণ। সার্টিফিকেটের অখণ্ডতা যাচাই করতে আইডি দিন।",
    ver_placeholder: "সার্টিফিকেট আইডি দিন (যেমন d2cfe4d4...)",
    ver_btn: "যাচাই",
    ver_scanning: "স্ক্যান হচ্ছে...",
    ver_step1_title: "আইডি খুঁজুন",
    ver_step1_desc: "আপনার সার্টিফিকেটের নিচে UUID খুঁজুন।",
    ver_step2_title: "অনুসন্ধান",
    ver_step2_desc: "সিস্টেম তাৎক্ষণিকভাবে ব্লকচেইন চেক করে।",
    ver_step3_title: "বৈধতা",
    ver_step3_desc: "ক্রিপ্টোগ্রাফিক প্রমাণ এবং স্বাক্ষর দেখুন।",
    ver_res_back: "ফিরে যান",
    ver_res_title: "যাচাইকরণ ফলাফল",
    ver_res_auth: "আসল নথি",
    ver_res_inv: "অবৈধ নথি",
    ver_res_rec: "প্রাপক",
    ver_res_date: "ইস্যু তারিখ",
    ver_res_type: "ধরন",
    ver_view_chain: "চেইনে দেখুন",

    // --- Dropdown Options ---
    "Degree Certificate": "ডিগ্রি সার্টিফিকেট",
    "Diploma Certificate": "ডিপ্লোমা সার্টিফিকেট",
    "Marksheet / Transcript": "মার্কশিট / প্রতিলিপি",
    "Course Completion": "কোর্স সমাপ্তি",
    "Research Grant": "গবেষণা অনুদান",
    "Skill Certification": "দক্ষতা সনদ",
    "Training Completion": "প্রশিক্ষণ সমাপ্তি",
    "Workshop / Bootcamp": "কর্মশালা / বুটক্যাম্প",
    "Language Proficiency": "ভাষাগত দক্ষতা",
    "Experience Letter": "অভিজ্ঞতার সনদ",
    "Internship Certificate": "ইন্টার্নশিপ সার্টিফিকেট",
    "Employment Verification": "চাকরি যাচাইকরণ",
    "Recommendation Letter": "সুপারিশ পত্র",
    "Professional License": "পেশাগত লাইসেন্স",
    "Government Authorization": "সরকারি অনুমোদন",
    "Regulatory Certificate": "নিয়ন্ত্রক সনদ",
    "Identity Proof": "পরিচয় প্রমাণ",
    "Gig Work Record": "গিগ কাজের রেকর্ড",
    "Platform Skill Rating": "প্ল্যাটফর্ম দক্ষতা রেটিং",
    "Work History Summary": "কাজের ইতিহাসের সারাংশ",
    "Project Completion": "প্রকল্প সমাপ্তি",
    "Certificate of Completion": "সমাপ্তির সনদ",
    "Certificate of Achievement": "অর্জনের সনদ",
    "Certificate of Participation": "অংশগ্রহণের সনদ",
    "Certificate of Excellence": "শ্রেষ্ঠত্বের সনদ",
    "Training Certificate": "প্রশিক্ষণ সনদ",
    "Official License": "অফিসিয়াল লাইসেন্স",
    "Verification Letter": "যাচাইকরণ পত্র"
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్", issue: "జారీ", verify: "ధృవీకరణ", myCerts: "నా సర్టిఫికెట్లు", connect: "కనెక్ట్", disconnect: "డిస్కనెక్ట్",
    heroTitle: "డిజిటల్ నమ్మకం,", heroSubtitle: "సరళీకృతం.", heroDesc: "OpenCred ధృవీకరణలో స్పష్టతను తెస్తుంది. సురక్షితమైనది.",
    issueTitle: "సర్టిఫికెట్ జారీ", issueDesc: "బ్లాక్‌చెయిన్ ఆధారాలను పంపండి.",
    verifyTitle: "ప్రామాణికత", verifyDesc: "ఏదైనా సర్టిఫికెట్‌ను తక్షణమే ధృవీకరించండి.",
    walletTitle: "డిజిటల్ వాలెట్", walletDesc: "విజయాలను భద్రంగా నిర్వహించండి.",

    iss_pageTitle: "సర్టిఫికెట్ జారీ", iss_pageSubtitle: "బ్లాక్‌చెయిన్‌లో రికార్డులను భద్రపరచండి.", iss_guideBtn: "గైడ్ చదవండి",
    iss_single: "ఒకటి", iss_bulk: "బల్క్", iss_step1: "వర్గీకరణ", iss_step2: "గ్రహీత", iss_step3: "వివరాలు",
    iss_cat: "వర్గం", iss_subcat: "ఉప-వర్గం", iss_temp: "టెంప్లేట్", iss_name: "పూర్తి పేరు", iss_wallet: "వాలెట్ చిరునామా",
    iss_date: "తేదీ", iss_btn: "జారీ చేయండి", iss_btn_processing: "ప్రాసెసింగ్...", iss_bulk_drop: "ఎక్సెల్ ఫైల్", iss_bulk_btn: "ప్రారంభించండి",
    iss_select_cat: "వివరాల కోసం వర్గాన్ని ఎంచుకోండి", iss_event: "ఈవెంట్ పేరు",
    lbl_course: "కోర్సు", lbl_org: "సంస్థ", lbl_grade: "గ్రేడ్", lbl_ref: "రిఫరెన్స్", lbl_achievements: "విజయాలు",
    cat_academic: "విద్యా అర్హతలు", cat_skill: "నైపుణ్యాలు", cat_employment: "ఉద్యోగ రికార్డు", cat_gov: "ప్రభుత్వ ఐడి", cat_gig: "గిగ్ వర్క్",

    ver_immutable: "శాశ్వతమైనది",
    ver_pageTitle: "ప్రామాణికతను సరిచూడండి.",
    ver_pageSubtitle: "తక్షణ, నమ్మకమైన ధృవీకరణ. సర్టిఫికేట్ సమగ్రతను ధృవీకరించడానికి IDని నమోదు చేయండి.",
    ver_placeholder: "సర్టిఫికేట్ IDని అతికించండి (ఉదా. d2cfe4d4...)",
    ver_btn: "ధృవీకరించండి",
    ver_scanning: "స్కానింగ్...",
    ver_step1_title: "IDని కనుగొనండి",
    ver_step1_desc: "మీ సర్టిఫికేట్ దిగువన UUIDని కనుగొనండి.",
    ver_step2_title: "శోధన",
    ver_step2_desc: "సిస్టమ్ తక్షణమే బ్లాక్‌చెయిన్‌ను శోధిస్తుంది.",
    ver_step3_title: "ధృవీకరించండి",
    ver_step3_desc: "క్రిప్టోగ్రాఫిక్ రుజువులు మరియు సంతకాలను వీక్షించండి.",
    ver_res_back: "వెనుకకు",
    ver_res_title: "ధృవీకరణ ఫలితం",
    ver_res_auth: "అసలైన పత్రం",
    ver_res_inv: "చెల్లని పత్రం",
    ver_res_rec: "గ్రహీత",
    ver_res_date: "జారీ తేదీ",
    ver_res_type: "రకం",
    ver_view_chain: "చైన్‌లో చూడండి",

    // --- Dropdown Options ---
    "Degree Certificate": "డిగ్రీ సర్టిఫికేట్",
    "Diploma Certificate": "డిప్లొమా సర్టిఫికేట్",
    "Marksheet / Transcript": "మార్కుల జాబితా / ట్రాన్స్క్రిప్ట్",
    "Course Completion": "కోర్సు పూర్తి",
    "Research Grant": "పరిశోధన గ్రాంట్",
    "Skill Certification": "నైపుణ్య ధృవీకరణ",
    "Training Completion": "శిక్షణ పూర్తి",
    "Workshop / Bootcamp": "వర్క్‌షాప్ / బూట్‌క్యాంప్",
    "Language Proficiency": "భాషా నైపుణ్యం",
    "Experience Letter": "అనుభవ లేఖ",
    "Internship Certificate": "ఇంటర్న్‌షిప్ సర్టిఫికేట్",
    "Employment Verification": "ఉద్యోగ ధృవీకరణ",
    "Recommendation Letter": "సిఫార్సు లేఖ",
    "Professional License": "వృత్తిపరమైన లైసెన్స్",
    "Government Authorization": "ప్రభుత్వ అనుమతి",
    "Regulatory Certificate": "నియంత్రణ సర్టిఫికేట్",
    "Identity Proof": "గుర్తింపు రుజువు",
    "Gig Work Record": "గిగ్ వర్క్ రికార్డ్",
    "Platform Skill Rating": "ప్లాట్‌ఫారమ్ స్కిల్ రేటింగ్",
    "Work History Summary": "పని చరిత్ర సారాంశం",
    "Project Completion": "ప్రాజెక్ట్ పూర్తి",
    "Certificate of Completion": "పూర్తి చేసిన సర్టిఫికేట్",
    "Certificate of Achievement": "విజయ సర్టిఫికేట్",
    "Certificate of Participation": "పాల్గొన్న సర్టిఫికేట్",
    "Certificate of Excellence": "ఎక్సలెన్స్ సర్టిఫికేట్",
    "Training Certificate": "శిక్షణ సర్టిఫికేట్",
    "Official License": "అధికారిక లైసెన్స్",
    "Verification Letter": "ధృవీకరణ లేఖ"
  },
  mr: {
    dashboard: "डॅशबोर्ड", issue: "जारी करा", verify: "पडताळणी", myCerts: "प्रमाणपत्रे", connect: "जोडा", disconnect: "डिस्कनेक्ट",
    heroTitle: "डिजिटल विश्वास,", heroSubtitle: "सोपे केले.", heroDesc: "OpenCred प्रमाणपत्रात स्पष्टता आणते. सुरक्षित.",
    issueTitle: "प्रमाणपत्र जारी", issueDesc: "ब्लॉकचेन प्रमाणपत्रे पाठवा.",
    verifyTitle: "सत्यता पडताळा", verifyDesc: "त्वरित सत्यापित करा.",
    walletTitle: "डिजिटल वॉलेट", walletDesc: "यश सुरक्षितपणे व्यवस्थापित करा.",

    iss_pageTitle: "प्रमाणपत्रे जारी", iss_pageSubtitle: "ब्लॉकचेनवर रेकॉर्ड ठेवा.", iss_guideBtn: "गाइड वाचा",
    iss_single: "एकल", iss_bulk: "बल्क", iss_step1: "वर्गीकरण", iss_step2: "प्राप्तकर्ता", iss_step3: "तपशील",
    iss_cat: "श्रेणी", iss_subcat: "उप-श्रेणी", iss_temp: "टेम्पलेट", iss_name: "पूर्ण नाव", iss_wallet: "पत्ता",
    iss_date: "दिनांक", iss_btn: "जारी करा", iss_btn_processing: "प्रक्रिया...", iss_bulk_drop: "फाइल टाका", iss_bulk_btn: "सुरू करा",
    iss_select_cat: "श्रेणी निवडा", iss_event: "इव्हेंट",
    lbl_course: "कोर्स", lbl_org: "संस्था", lbl_grade: "ग्रेड", lbl_ref: "संदर्भ", lbl_achievements: "उपलब्धी",
    cat_academic: "शैक्षणिक", cat_skill: "कौशल्य", cat_employment: "नोकरी", cat_gov: "सरकारी", cat_gig: "गिग",

    ver_immutable: "अपरिवर्तनीय",
    ver_pageTitle: "सत्यता पडताळा.",
    ver_pageSubtitle: "त्वरित आणि सुरक्षित पडताळणी. प्रमाणपत्राची सत्यता तपासण्यासाठी आयडी टाका.",
    ver_placeholder: "प्रमाणपत्र आयडी पेस्ट करा (उदा. d2cfe4d4...)",
    ver_btn: "पडताळा",
    ver_scanning: "स्कॅनिंग...",
    ver_step1_title: "आयडी शोधा",
    ver_step1_desc: "प्रमाणपत्राच्या खाली UUID शोधा.",
    ver_step2_title: "इनपुट आणि शोध",
    ver_step2_desc: "सिस्टम त्वरित ब्लॉकचेन तपासते.",
    ver_step3_title: "मान्य करा",
    ver_step3_desc: "क्रिप्टोग्राफिक पुरावे आणि स्वाक्षरी पहा.",
    ver_res_back: "परत जा",
    ver_res_title: "पडताळणी निकाल",
    ver_res_auth: "अस्सल दस्तऐवज",
    ver_res_inv: "अवैध दस्तऐवज",
    ver_res_rec: "प्राप्तकर्ता",
    ver_res_date: "दिनांक",
    ver_res_type: "प्रकार",
    ver_view_chain: "चेनवर पहा",

    // --- Dropdown Options ---
    "Degree Certificate": "पदवी प्रमाणपत्र",
    "Diploma Certificate": "डिप्लोमा प्रमाणपत्र",
    "Marksheet / Transcript": "गुणपत्रिका",
    "Course Completion": "अभ्यासक्रम पूर्ण",
    "Research Grant": "संशोधन अनुदान",
    "Skill Certification": "कौशल्य प्रमाणपत्र",
    "Training Completion": "प्रशिक्षण पूर्ण",
    "Workshop / Bootcamp": "कार्यशाळा / बूटकॅम्प",
    "Language Proficiency": "भाषा प्रभुत्व",
    "Experience Letter": "अनुभव पत्र",
    "Internship Certificate": "इंटर्नशिप प्रमाणपत्र",
    "Employment Verification": "नोकरी पडताळणी",
    "Recommendation Letter": "शिफारस पत्र",
    "Professional License": "व्यावसायिक परवाना",
    "Government Authorization": "सरकारी प्राधिकरण",
    "Regulatory Certificate": "नियामक प्रमाणपत्र",
    "Identity Proof": "ओळख पुरावा",
    "Gig Work Record": "गिग वर्क रेकॉर्ड",
    "Platform Skill Rating": "प्लॅटफॉर्म स्किल रेटिंग",
    "Work History Summary": "कामाचा इतिहास",
    "Project Completion": "प्रकल्प पूर्ण",
    "Certificate of Completion": "पूर्ण केल्याचे प्रमाणपत्र",
    "Certificate of Achievement": "उपलब्धी प्रमाणपत्र",
    "Certificate of Participation": "सहभाग प्रमाणपत्र",
    "Certificate of Excellence": "उत्कृष्टता प्रमाणपत्र",
    "Training Certificate": "प्रशिक्षण प्रमाणपत्र",
    "Official License": "अधिकृत परवाना",
    "Verification Letter": "पडताळणी पत्र"
  },
  ta: {
    dashboard: "முகப்பு", issue: "வழங்குதல்", verify: "சரிபார்ப்பு", myCerts: "சான்றிதழ்கள்", connect: "இணைக்கவும்", disconnect: "துண்டிக்கவும்",
    heroTitle: "டிஜிட்டல் நம்பிக்கை,", heroSubtitle: "எளிமையானது.", heroDesc: "பாதுகாப்பான மற்றும் நம்பகமான சான்றிதழ்.",
    issueTitle: "சான்றிதழ் வழங்குதல்", issueDesc: "பிளாக்செயின் சான்றுகளை அனுப்பவும்.",
    verifyTitle: "சரிபார்க்கவும்", verifyDesc: "உடனடியாக சரிபார்க்கவும்.",
    walletTitle: "டிஜிட்டல் வாலட்", walletDesc: "சாதனைகளை நிர்வகிக்கவும்.",

    iss_pageTitle: "சான்றுகள் வழங்கவும்", iss_pageSubtitle: "பதிவுகளைச் சேர்க்கவும்.", iss_guideBtn: "வழிகாட்டி",
    iss_single: "தனி", iss_bulk: "மொத்தம்", iss_step1: "வகைப்பாடு", iss_step2: "பெறுநர்", iss_step3: "விவரங்கள்",
    iss_cat: "வகை", iss_subcat: "துணைப்பிரிவு", iss_temp: "வார்ப்புரு", iss_name: "பெயர்", iss_wallet: "முகவரி",
    iss_date: "தேதி", iss_btn: "வழங்கவும்", iss_btn_processing: "செயலாக்கம்...", iss_bulk_drop: "கோப்பு", iss_bulk_btn: "தொடங்கவும்",
    iss_select_cat: "வகையைத் தேர்ந்தெடுக்கவும்", iss_event: "நிகழ்வு",
    lbl_course: "பாடம்", lbl_org: "நிறுவனம்", lbl_grade: "மதிப்பெண்", lbl_ref: "குறிப்பு", lbl_achievements: "சாதனைகள்",
    cat_academic: "கல்வி", cat_skill: "திறன்", cat_employment: "வேலை", cat_gov: "அரசு", cat_gig: "கிக்",

    ver_immutable: "மாற்ற முடியாதது",
    ver_pageTitle: "நம்பகத்தன்மையை சரிபார்க்கவும்.",
    ver_pageSubtitle: "உடனடி சரிபார்ப்பு. சான்றிதழை உறுதிப்படுத்த ஐடியை உள்ளிடவும்.",
    ver_placeholder: "சான்றிதழ் ஐடியை உள்ளிடவும் (எ.கா. d2cfe4d4...)",
    ver_btn: "சரிபார்",
    ver_scanning: "ஸ்கேன் செய்கிறது...",
    ver_step1_title: "ஐடியைக் கண்டுபிடி",
    ver_step1_desc: "சான்றிதழின் கீழே உள்ள UUID ஐக் கண்டறியவும்.",
    ver_step2_title: "தேடல்",
    ver_step2_desc: "அமைப்பு பிளாக்செயினை உடனடியாக வினவுகிறது.",
    ver_step3_title: "உறுதிப்படுத்தவும்",
    ver_step3_desc: "கிரிப்டோகிராஃபிக் ஆதாரங்களைக் காண்க.",
    ver_res_back: "திரும்பச் செல்",
    ver_res_title: "சரிபார்ப்பு முடிவு",
    ver_res_auth: "உண்மையான ஆவணம்",
    ver_res_inv: "செல்லாத ஆவணம்",
    ver_res_rec: "பெறுநர்",
    ver_res_date: "தேதி",
    ver_res_type: "வகை",
    ver_view_chain: "செயினில் பார்",

    // --- Dropdown Options ---
    "Degree Certificate": "பட்டப் படிப்பு சான்றிதழ்",
    "Diploma Certificate": "டிப்ளமோ சான்றிதழ்",
    "Marksheet / Transcript": "மதிப்பெண் பட்டியல்",
    "Course Completion": "பாடம் முடித்தல்",
    "Research Grant": "ஆராய்ச்சி மானியம்",
    "Skill Certification": "திறன் சான்றிதழ்",
    "Training Completion": "பயிற்சி முடித்தல்",
    "Workshop / Bootcamp": "பயிலரங்கம் / பயிற்சி முகாம்",
    "Language Proficiency": "மொழித் திறன்",
    "Experience Letter": "அனுபவ சான்றிதழ்",
    "Internship Certificate": "பயிற்சி சான்றிதழ்",
    "Employment Verification": "வேலைவாய்ப்பு சரிபார்ப்பு",
    "Recommendation Letter": "பரிந்துரை கடிதம்",
    "Professional License": "தொழில்முறை உரிமம்",
    "Government Authorization": "அரசு அங்கீகாரம்",
    "Regulatory Certificate": "ஒழுங்குமுறை சான்றிதழ்",
    "Identity Proof": "அடையாள ஆதாரம்",
    "Gig Work Record": "கிக் வேலை பதிவு",
    "Platform Skill Rating": "தள திறன் மதிப்பீடு",
    "Work History Summary": "வேலை வரலாறு",
    "Project Completion": "திட்டம் முடித்தல்",
    "Certificate of Completion": "முடித்ததற்கான சான்றிதழ்",
    "Certificate of Achievement": "சாதனை சான்றிதழ்",
    "Certificate of Participation": "பங்கேற்பு சான்றிதழ்",
    "Certificate of Excellence": "சிறப்புச் சான்றிதழ்",
    "Training Certificate": "பயிற்சி சான்றிதழ்",
    "Official License": "அதிகாரப்பூர்வ உரிமம்",
    "Verification Letter": "சரிபார்ப்புக் கடிதம்"
  },
  gu: {
    dashboard: "ડેશબોર્ડ", issue: "ઇશ્યુ", verify: "ચકાસણી", myCerts: "પ્રમાણપત્રો", connect: "કનેક્ટ", disconnect: "ડિસ્કનેક્ટ",
    heroTitle: "ડિજિટલ વિશ્વાસ,", heroSubtitle: "સરળ.", heroDesc: "સુરક્ષિત અને ભરોસાપાત્ર પ્રમાણપત્ર.",
    issueTitle: "પ્રમાણપત્ર આપો", issueDesc: "બ્લોકચેન રેકોર્ડ્સ મોકલો.",
    verifyTitle: "અસલિયત તપાસો", verifyDesc: "તરત જ માન્ય કરો.",
    walletTitle: "ડિજિટલ વોલેટ", walletDesc: "સિદ્ધિઓ મેનેજ કરો.",

    iss_pageTitle: "ક્રેડેન્શિયલ્સ", iss_pageSubtitle: "રેકોર્ડ્સ મૂકો.", iss_guideBtn: "માર્ગદર્શિકા",
    iss_single: "એકલ", iss_bulk: "જથ્થાબંધ", iss_step1: "વર્ગીકરણ", iss_step2: "પ્રાપ્તકર્તા", iss_step3: "વિગતો",
    iss_cat: "શ્રેણી", iss_subcat: "પેટા-શ્રેણી", iss_temp: "ટેમ્પલેટ", iss_name: "નામ", iss_wallet: "સરનામું",
    iss_date: "તારીખ", iss_btn: "આપો", iss_btn_processing: "પ્રક્રિયા...", iss_bulk_drop: "ફાઇલ", iss_bulk_btn: "શરૂ કરો",
    iss_select_cat: "શ્રેણી પસંદ કરો", iss_event: "ઇવેન્ટ",
    lbl_course: "કોર્સ", lbl_org: "સંસ્થા", lbl_grade: "ગ્રેડ", lbl_ref: "સંદર્ભ", lbl_achievements: "સિદ્ધિઓ",
    cat_academic: "શૈક્ષણિક", cat_skill: "કૌશલ્ય", cat_employment: "રોજગાર", cat_gov: "સરકારી", cat_gig: "ગીગ",

    ver_immutable: "અપરિવર્તનીય",
    ver_pageTitle: "અસલિયત તપાસો.",
    ver_pageSubtitle: "ત્વરિત ચકાસણી. પ્રમાણપત્રને માન્ય કરવા માટે ID દાખલ કરો.",
    ver_placeholder: "પ્રમાણપત્ર ID પેસ્ટ કરો (દા.ત. d2cfe4d4...)",
    ver_btn: "ચકાસો",
    ver_scanning: "સ્કેનિંગ...",
    ver_step1_title: "ID શોધો",
    ver_step1_desc: "પ્રમાણપત્રના તળિયે UUID શોધો.",
    ver_step2_title: "ઇનપુટ અને શોધ",
    ver_step2_desc: "સિસ્ટમ બ્લોકચેન લેઝરને ક્વેરી કરે છે.",
    ver_step3_title: "માન્ય કરો",
    ver_step3_desc: "ક્રિપ્ટોગ્રાફિક પુરાવા જુઓ.",
    ver_res_back: "પાછા જાઓ",
    ver_res_title: "ચકાસણી પરિણામ",
    ver_res_auth: "અસલ દસ્તાવેજ",
    ver_res_inv: "અમાન્ય દસ્તાવેજ",
    ver_res_rec: "પ્રાપ્તકર્તા",
    ver_res_date: "તારીખ",
    ver_res_type: "પ્રકાર",
    ver_view_chain: "ચેઇન પર જુઓ",

    // --- Dropdown Options ---
    "Degree Certificate": "ડિગ્રી પ્રમાણપત્ર",
    "Diploma Certificate": "ડિપ્લોમા પ્રમાણપત્ર",
    "Marksheet / Transcript": "ગુણપત્રક",
    "Course Completion": "કોર્સ પૂર્ણતા",
    "Research Grant": "સંશોધન ગ્રાન્ટ",
    "Skill Certification": "કૌશલ્ય પ્રમાણપત્ર",
    "Training Completion": "તાલીમ પૂર્ણતા",
    "Workshop / Bootcamp": "વર્કશોપ / બૂટકેમ્પ",
    "Language Proficiency": "ભાષા પ્રાવીણ્ય",
    "Experience Letter": "અનુભવ પત્ર",
    "Internship Certificate": "ઇન્ટર્નશીપ પ્રમાણપત્ર",
    "Employment Verification": "રોજગાર ચકાસણી",
    "Recommendation Letter": "ભલામણ પત્ર",
    "Professional License": "વ્યાવસાયિક લાઇસન્સ",
    "Government Authorization": "સરકારી અધિકૃતતા",
    "Regulatory Certificate": "નિયમનકારી પ્રમાણપત્ર",
    "Identity Proof": "ઓળખનો પુરાવો",
    "Gig Work Record": "ગીગ વર્ક રેકોર્ડ",
    "Platform Skill Rating": "પ્લેટફોર્મ કૌશલ્ય રેટિંગ",
    "Work History Summary": "કાર્ય ઇતિહાસ",
    "Project Completion": "પ્રોજેક્ટ પૂર્ણતા",
    "Certificate of Completion": "પૂર્ણતા પ્રમાણપત્ર",
    "Certificate of Achievement": "સિદ્ધિ પ્રમાણપત્ર",
    "Certificate of Participation": "ભાગીદારી પ્રમાણપત્ર",
    "Certificate of Excellence": "શ્રેષ્ઠતા પ્રમાણપત્ર",
    "Training Certificate": "તાલીમ પ્રમાણપત્ર",
    "Official License": "સત્તાવાર લાઇસન્સ",
    "Verification Letter": "ચકાસણી પત્ર"
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", issue: "ವಿತರಿಸಿ", verify: "ಪರಿಶೀಲಿಸಿ", myCerts: "ಪ್ರಮಾಣಪತ್ರಗಳು", connect: "ಸಂಪರ್ಕಿಸಿ", disconnect: "ಕಡಿತಗೊಳಿಸಿ",
    heroTitle: "ಡಿಜિટಲ್ ನಂಬಿಕೆ,", heroSubtitle: "ಸರಳ.", heroDesc: "ಸುರಕ್ಷಿತ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ.",
    issueTitle: "ಪ್ರಮಾಣಪತ್ರ ವಿತರಣೆ", issueDesc: "ಬ್ಲಾಕ್‌ಚೈನ್ ದಾಖಲೆಗಳನ್ನು ಕಳುಹಿಸಿ.",
    verifyTitle: "ದೃಢೀಕರಣ", verifyDesc: "ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ.",
    walletTitle: "ಡಿಜಿಟಲ್ ವಾಲೆಟ್", walletDesc: "ಸಾಧನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",

    iss_pageTitle: "ರುಜುವಾತುಗಳು", iss_pageSubtitle: "ದಾಖಲೆಗಳನ್ನು ಹಾಕಿ.", iss_guideBtn: "ಮಾರ್ಗದರ್ಶಿ",
    iss_single: "ಒಂದೇ", iss_bulk: "ಬಲ್ಕ್", iss_step1: "ವರ್ಗೀಕರಣ", iss_step2: "ಸ್ವೀಕರಿಸುವವರು", iss_step3: "ವಿವರಗಳು",
    iss_cat: "ವರ್ಗ", iss_subcat: "ಉಪ-ವರ್ಗ", iss_temp: "ಟೆಂಪ್ಲೇಟ್", iss_name: "ಹೆಸರು", iss_wallet: "ವಿಳಾಸ",
    iss_date: "ದಿನಾಂಕ", iss_btn: "ವಿತರಿಸಿ", iss_btn_processing: "ಪ್ರಕ್ರಿಯೆ...", iss_bulk_drop: "ಫೈಲ್", iss_bulk_btn: "ಪ್ರಾರಂಭಿಸಿ",
    iss_select_cat: "ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ", iss_event: "ಈವೆಂಟ್",
    lbl_course: "ಕೋರ್ಸ್", lbl_org: "ಸಂಸ್ಥೆ", lbl_grade: "ಗ್ರೇಡ್", lbl_ref: "ಉಲ್ಲೇಖ", lbl_achievements: "ಸಾಧನೆಗಳು",
    cat_academic: "ಶೈಕ್ಷಣಿಕ", cat_skill: "ಕೌಶಲ್ಯ", cat_employment: "ಉದ್ಯೋಗ", cat_gov: "ಸರ್ಕಾರಿ", cat_gig: "ಗಿಗ್",

    ver_immutable: "ಬದಲಾಯಿಸಲಾಗದ",
    ver_pageTitle: "ದೃಢೀಕರಣ ಪರಿಶೀಲಿಸಿ.",
    ver_pageSubtitle: "ತ್ವರಿತ ಪರಿಶೀಲನೆ. ಪ್ರಮಾಣಪತ್ರವನ್ನು ಮೌಲ್ಯೀಕರಿಸಲು ID ನಮೂದಿಸಿ.",
    ver_placeholder: "ಪ್ರಮಾಣಪತ್ರ ID ಅಂಟಿಸಿ (ಉದಾ. d2cfe4d4...)",
    ver_btn: "ಪರಿಶೀಲಿಸಿ",
    ver_scanning: "ಸ್ಕ್ಯಾನಿಂಗ್...",
    ver_step1_title: "ID ಹುಡುಕಿ",
    ver_step1_desc: "ಪ್ರಮಾಣಪತ್ರದ ಕೆಳಭಾಗದಲ್ಲಿ UUID ಹುಡುಕಿ.",
    ver_step2_title: "ಹುಡುಕಾಟ",
    ver_step2_desc: "ಸಿಸ್ಟಮ್ ಬ್ಲಾಕ್‌ಚೈನ್ ಪರಿಶೀಲಿಸುತ್ತದೆ.",
    ver_step3_title: "ಮೌಲ್ಯೀಕರಿಸಿ",
    ver_step3_desc: "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಪುರಾವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
    ver_res_back: "ಹಿಂದೆ",
    ver_res_title: "ಪರಿಶೀಲನೆ ಫಲಿತಾಂಶ",
    ver_res_auth: "ಅಧಿಕೃತ ದಾಖಲೆ",
    ver_res_inv: "ಅಮಾನ್ಯ ದಾಖಲೆ",
    ver_res_rec: "ಸ್ವೀಕರಿಸುವವರು",
    ver_res_date: "ದಿನಾಂಕ",
    ver_res_type: "ಮಾದರಿ",
    ver_view_chain: "ಚೈನ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ",

    // --- Dropdown Options ---
    "Degree Certificate": "ಪದವಿ ಪ್ರಮಾಣಪತ್ರ",
    "Diploma Certificate": "ಡಿಪ್ಲೊಮಾ ಪ್ರಮಾಣಪತ್ರ",
    "Marksheet / Transcript": "ಅಂಕಪಟ್ಟಿ",
    "Course Completion": "ಕೋರ್ಸ್ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ",
    "Research Grant": "ಸಂಶೋಧನಾ ಅನುದಾನ",
    "Skill Certification": "ಕೌಶಲ್ಯ ಪ್ರಮಾಣೀಕರಣ",
    "Training Completion": "ತರಬೇತಿ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ",
    "Workshop / Bootcamp": "ಕಾರ್ಯಾಗಾರ / ಬೂಟ್‌ಕ್ಯಾಂಪ್",
    "Language Proficiency": "ಭಾಷಾ ಪ್ರಾವೀಣ್ಯತೆ",
    "Experience Letter": "ಅನುಭವ ಪತ್ರ",
    "Internship Certificate": "ಇಂಟರ್ನ್‌ಶಿಪ್ ಪ್ರಮಾಣಪತ್ರ",
    "Employment Verification": "ಉದ್ಯೋಗ ಪರಿಶೀಲನೆ",
    "Recommendation Letter": "ಶಿಫಾರಸು ಪತ್ರ",
    "Professional License": "ವೃತ್ತಿಪರ ಪರವಾನಗಿ",
    "Government Authorization": "ಸರ್ಕಾರಿ ಅನುಮೋದನೆ",
    "Regulatory Certificate": "ನಿಯಂತ್ರಕ ಪ್ರಮಾಣಪತ್ರ",
    "Identity Proof": "ಗುರುತಿನ ಪುರಾವೆ",
    "Gig Work Record": "ಗಿಗ್ ಕೆಲಸದ ದಾಖಲೆ",
    "Platform Skill Rating": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಕೌಶಲ್ಯ ರೇಟಿಂಗ್",
    "Work History Summary": "ಕೆಲಸದ ಇತಿಹಾಸ",
    "Project Completion": "ಯೋಜನೆ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ",
    "Certificate of Completion": "ಪೂರ್ಣಗೊಳಿಸುವಿಕೆಯ ಪ್ರಮಾಣಪತ್ರ",
    "Certificate of Achievement": "ಸಾಧನೆಯ ಪ್ರಮಾಣಪತ್ರ",
    "Certificate of Participation": "ಭಾಗವಹಿಸುವಿಕೆ ಪ್ರಮಾಣಪತ್ರ",
    "Certificate of Excellence": "ಶ್ರೇಷ್ಠತೆಯ ಪ್ರಮಾಣಪತ್ರ",
    "Training Certificate": "ತರಬೇತಿ ಪ್ರಮಾಣಪತ್ರ",
    "Official License": "ಅಧಿಕೃತ ಪರವಾನಗಿ",
    "Verification Letter": "ಪರಿಶೀಲನೆ ಪತ್ರ"
  },
  ml: {
    dashboard: "ഡാഷ്ബോർഡ്", issue: "ഇഷ്യു", verify: "പരിശോധന", myCerts: "സർട്ടിഫിക്കറ്റുകൾ", connect: "ബന്ധിപ്പിക്കുക", disconnect: "വിച്ഛേദിക്കുക",
    heroTitle: "ഡിജിറ്റൽ വിശ്വാസം,", heroSubtitle: "ലളിതം.", heroDesc: "സുരക്ഷിതവും വിശ്വസനീയവും.",
    issueTitle: "സർട്ടിഫിക്കറ്റ്", issueDesc: "ബ്ലോക്ക്ചെയിൻ രേഖകൾ അയയ്ക്കുക.",
    verifyTitle: "ആധികാരികത", verifyDesc: "തൽക്ഷണം പരിശോധിക്കുക.",
    walletTitle: "ഡിജിറ്റൽ വാലറ്റ്", walletDesc: "നേട്ടങ്ങൾ കൈകാര്യം ചെയ്യുക.",

    iss_pageTitle: "രേഖകൾ നൽകുക", iss_pageSubtitle: "രേഖകൾ സൂക്ഷിക്കുക.", iss_guideBtn: "ഗൈഡ്",
    iss_single: "ഒരെണ്ണം", iss_bulk: "ഒന്നിച്ചുള്ള", iss_step1: "തരംതിരിക്കൽ", iss_step2: "സ്വീകർത്താവ്", iss_step3: "വിശദാംശങ്ങൾ",
    iss_cat: "വിഭാഗം", iss_subcat: "ഉപവിഭാഗം", iss_temp: "ടെംപ്ലേറ്റ്", iss_name: "പേര്", iss_wallet: "വിലാസം",
    iss_date: "തീയതി", iss_btn: "നൽകുക", iss_btn_processing: "പ്രോസസ്സിംഗ്...", iss_bulk_drop: "ഫയൽ", iss_bulk_btn: "ആരംഭിക്കുക",
    iss_select_cat: "വിഭാഗം തിരഞ്ഞെടുക്കുക", iss_event: "ഇവന്റ്",
    lbl_course: "കോഴ്സ്", lbl_org: "സ്ഥാപനം", lbl_grade: "ഗ്രേഡ്", lbl_ref: "റഫറൻസ്", lbl_achievements: "നേട്ടങ്ങൾ",
    cat_academic: "വിദ്യാഭ്യാസം", cat_skill: "നൈപുണ്യം", cat_employment: "തൊഴിൽ", cat_gov: "സർക്കാർ", cat_gig: "ഗിഗ്",

    ver_immutable: "മാറ്റമില്ലാത്തത്",
    ver_pageTitle: "ആധികാരികത പരിശോധിക്കുക.",
    ver_pageSubtitle: "തൽക്ഷണ പരിശോധന. സർട്ടിഫിക്കറ്റ് സാധൂകരിക്കാൻ ID നൽകുക.",
    ver_placeholder: "സർട്ടിഫിക്കറ്റ് ID നൽകുക (ഉദാ. d2cfe4d4...)",
    ver_btn: "പരിശോധിക്കുക",
    ver_scanning: "സ്കാനിംഗ്...",
    ver_step1_title: "ID കണ്ടെത്തുക",
    ver_step1_desc: "സർട്ടിഫിക്കറ്റിന് താഴെയുള്ള UUID കണ്ടെത്തുക.",
    ver_step2_title: "തിരയുക",
    ver_step2_desc: "സിസ്റ്റം ബ്ലോക്ക്ചെയിനിൽ തിരയുന്നു.",
    ver_step3_title: "സാധൂകരിക്കുക",
    ver_step3_desc: "ക്രിപ്റ്റോഗ്രാഫിക് തെളിവുകൾ കാണുക.",
    ver_res_back: "തിരികെ",
    ver_res_title: "പരിശോധനാ ഫലം",
    ver_res_auth: "ആധികാരിക രേഖ",
    ver_res_inv: "അസാധുവായ രേഖ",
    ver_res_rec: "സ്വീകർത്താവ്",
    ver_res_date: "തീയതി",
    ver_res_type: "തരം",
    ver_view_chain: "ചെയിനിൽ കാണുക",

    // --- Dropdown Options ---
    "Degree Certificate": "ബിരുദ സർട്ടിഫിക്കറ്റ്",
    "Diploma Certificate": "ഡിപ്ലോമ സർട്ടിഫിക്കറ്റ്",
    "Marksheet / Transcript": "മാർക്ക് ലിസ്റ്റ്",
    "Course Completion": "കോഴ്സ് പൂർത്തിയാക്കൽ",
    "Research Grant": "ഗവേഷണ ഗ്രാന്റ്",
    "Skill Certification": "നൈപുണ്യ സർട്ടിഫിക്കറ്റ്",
    "Training Completion": "പരിശീലനം പൂർത്തിയാക്കൽ",
    "Workshop / Bootcamp": "ശിൽപ്പശാല / ബൂട്ട് ക്യാമ്പ്",
    "Language Proficiency": "ഭാഷാ വൈദഗ്ദ്ധ്യം",
    "Experience Letter": "പ്രവൃത്തിപരിചയ കത്ത്",
    "Internship Certificate": "ഇന്റേൺഷിപ്പ് സർട്ടിഫിക്കറ്റ്",
    "Employment Verification": "തൊഴിൽ പരിശോധന",
    "Recommendation Letter": "ശുപാർശ കത്ത്",
    "Professional License": "പ്രൊഫഷണൽ ലൈസൻസ്",
    "Government Authorization": "സർക്കാർ അംഗീകാരം",
    "Regulatory Certificate": "റെഗുലേറ്ററി സർട്ടിഫിക്കറ്റ്",
    "Identity Proof": "തിരിച്ചറിയൽ രേഖ",
    "Gig Work Record": "ഗിഗ് വർക്ക് റെക്കോർഡ്",
    "Platform Skill Rating": "പ്ലാറ്റ്‌ഫോം സ്കിൽ റേറ്റിംഗ്",
    "Work History Summary": "ജോലി ചരിത്രം",
    "Project Completion": "പദ്ധതി പൂർത്തീകരണം",
    "Certificate of Completion": "പൂർത്തീകരണ സർട്ടിഫിക്കറ്റ്",
    "Certificate of Achievement": "നേട്ടങ്ങളുടെ സർട്ടിഫിക്കറ്റ്",
    "Certificate of Participation": "പങ്കാളിത്ത സർട്ടിഫിക്കറ്റ്",
    "Certificate of Excellence": "മികവിന്റെ സർട്ടിഫിക്കറ്റ്",
    "Training Certificate": "പരിശീലന സർട്ടിഫിക്കറ്റ്",
    "Official License": "ഔദ്യോഗിക ലൈസൻസ്",
    "Verification Letter": "പരിശോധന കത്ത്"
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ", issue: "ਜਾਰੀ", verify: "ਜਾਂਚ", myCerts: "ਸਰਟੀਫਿਕੇਟ", connect: "ਕਨੈਕਟ", disconnect: "ਡਿਸਕਨੈਕਟ",
    heroTitle: "ਡਿਜੀਟਲ ਭਰੋਸਾ,", heroSubtitle: "ਸਰਲ.", heroDesc: "ਸੁਰੱਖਿਅਤ ਅਤੇ ਭਰੋਸੇਮੰਦ।",
    issueTitle: "ਸਰਟੀਫਿਕੇਟ", issueDesc: "ਬਲਾਕਚੈਨ ਰਿਕਾਰਡ ਭੇਜੋ।",
    verifyTitle: "ਪ੍ਰਮਾਣਿਕਤਾ", verifyDesc: "ਤੁਰੰਤ ਜਾਂਚ ਕਰੋ।",
    walletTitle: "ਡਿਜੀਟਲ ਵਾਲਿਟ", walletDesc: "ਪ੍ਰਾਪਤੀਆਂ ਸੰਭਾਲੋ।",

    iss_pageTitle: "ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ", iss_pageSubtitle: "ਰਿਕਾਰਡ ਸੁਰੱਖਿਅਤ ਕਰੋ।", iss_guideBtn: "ਗਾਈਡ",
    iss_single: "ਇਕੱਲਾ", iss_bulk: "ਥੋਕ", iss_step1: "ਸ਼੍ਰੇਣੀ", iss_step2: "ਪ੍ਰਾਪਤਕਰਤਾ", iss_step3: "ਵੇਰਵੇ",
    iss_cat: "ਸ਼੍ਰੇਣੀ", iss_subcat: "ਉਪ-ਸ਼੍ਰੇਣੀ", iss_temp: "ਟੈਂਪਲੇਟ", iss_name: "ਨਾਮ", iss_wallet: "ਪਤਾ",
    iss_date: "ਮਿਤੀ", iss_btn: "ਜਾਰੀ ਕਰੋ", iss_btn_processing: "ਕਾਰਵਾਈ...", iss_bulk_drop: "ਫਾਈਲ", iss_bulk_btn: "ਸ਼ੁਰੂ ਕਰੋ",
    iss_select_cat: "ਸ਼੍ਰੇਣੀ ਚੁਣੋ", iss_event: "ਈਵੈਂਟ",
    lbl_course: "ਕੋਰਸ", lbl_org: "ਸੰਸਥਾ", lbl_grade: "ਗ੍ਰੇਡ", lbl_ref: "ਹਵਾਲਾ", lbl_achievements: "ਪ੍ਰਾਪਤੀਆਂ",
    cat_academic: "ਅਕਾਦਮਿਕ", cat_skill: "ਹੁਨਰ", cat_employment: "ਰੁਜ਼ਗਾਰ", cat_gov: "ਸਰਕਾਰੀ", cat_gig: "ਗਿਗ",

    ver_immutable: "ਅਟੱਲ",
    ver_pageTitle: "ਪ੍ਰਮਾਣਿਕਤਾ ਦੀ ਜਾਂਚ ਕਰੋ।",
    ver_pageSubtitle: "ਤੁਰੰਤ ਜਾਂਚ। ਸਰਟੀਫਿਕੇਟ ਨੂੰ ਪ੍ਰਮਾਣਿਤ ਕਰਨ ਲਈ ID ਦਰਜ ਕਰੋ।",
    ver_placeholder: "ਸਰਟੀਫਿਕੇਟ ID ਪੇਸਟ ਕਰੋ (ਜਿਵੇਂ d2cfe4d4...)",
    ver_btn: "ਜਾਂਚ ਕਰੋ",
    ver_scanning: "ਸਕੈਨਿੰਗ...",
    ver_step1_title: "ID ਲੱਭੋ",
    ver_step1_desc: "ਸਰਟੀਫਿਕੇਟ ਦੇ ਹੇਠਾਂ UUID ਲੱਭੋ।",
    ver_step2_title: "ਖੋਜ",
    ver_step2_desc: "ਸਿਸਟਮ ਬਲਾਕਚੈਨ ਦੀ ਜਾਂਚ ਕਰਦਾ ਹੈ।",
    ver_step3_title: "ਪ੍ਰਮਾਣਿਤ ਕਰੋ",
    ver_step3_desc: "ਕ੍ਰਿਪਟੋਗ੍ਰਾਫਿਕ ਸਬੂਤ ਦੇਖੋ।",
    ver_res_back: "ਵਾਪਸ ਜਾਓ",
    ver_res_title: "ਨਤੀਜਾ",
    ver_res_auth: "ਅਸਲੀ ਦਸਤਾਵੇਜ਼",
    ver_res_inv: "ਗਲਤ ਦਸਤਾਵੇਜ਼",
    ver_res_rec: "ਪ੍ਰਾਪਤਕਰਤਾ",
    ver_res_date: "ਮਿਤੀ",
    ver_res_type: "ਕਿਸਮ",
    ver_view_chain: "ਚੇਨ 'ਤੇ ਦੇਖੋ",

    // --- Dropdown Options ---
    "Degree Certificate": "ਡਿਗਰੀ ਸਰਟੀਫਿਕੇਟ",
    "Diploma Certificate": "ਡਿਪਲੋਮਾ ਸਰਟੀਫਿਕੇਟ",
    "Marksheet / Transcript": "ਅੰਕ ਸੂਚੀ",
    "Course Completion": "ਕੋਰਸ ਪੂਰਾ",
    "Research Grant": "ਖੋਜ ਗ੍ਰਾਂਟ",
    "Skill Certification": "ਹੁਨਰ ਸਰਟੀਫਿਕੇਟ",
    "Training Completion": "ਸਿਖਲਾਈ ਪੂਰੀ",
    "Workshop / Bootcamp": "ਵਰਕਸ਼ਾਪ / ਬੂਟਕੈਂਪ",
    "Language Proficiency": "ਭਾਸ਼ਾ ਦੀ ਮੁਹਾਰਤ",
    "Experience Letter": "ਤਜਰਬਾ ਪੱਤਰ",
    "Internship Certificate": "ਇੰਟਰਨਸ਼ਿਪ ਸਰਟੀਫਿਕੇਟ",
    "Employment Verification": "ਰੁਜ਼ਗਾਰ ਤਸਦੀਕ",
    "Recommendation Letter": "ਸਿਫਾਰਸ਼ ਪੱਤਰ",
    "Professional License": "ਪੇਸ਼ੇਵਰ ਲਾਇਸੈਂਸ",
    "Government Authorization": "ਸਰਕਾਰੀ ਅਧਿਕਾਰ",
    "Regulatory Certificate": "ਰੈਗੂਲੇਟਰੀ ਸਰਟੀਫਿਕੇਟ",
    "Identity Proof": "ਪਛਾਣ ਸਬੂਤ",
    "Gig Work Record": "ਗਿਗ ਵਰਕ ਰਿਕਾਰਡ",
    "Platform Skill Rating": "ਪਲੇਟਫਾਰਮ ਹੁਨਰ ਰੇਟਿੰਗ",
    "Work History Summary": "ਕੰਮ ਦਾ ਇਤਿਹਾਸ",
    "Project Completion": "ਪ੍ਰੋਜੈਕਟ ਪੂਰਾ",
    "Certificate of Completion": "ਸੰਪੂਰਨਤਾ ਸਰਟੀਫਿਕੇਟ",
    "Certificate of Achievement": "ਪ੍ਰਾਪਤੀ ਸਰਟੀਫਿਕੇਟ",
    "Certificate of Participation": "ਭਾਗੀਦਾਰੀ ਸਰਟੀਫਿਕੇਟ",
    "Certificate of Excellence": "ਉੱਤਮਤਾ ਸਰਟੀਫਿਕੇਟ",
    "Training Certificate": "ਸਿਖਲਾਈ ਸਰਟੀਫਿਕੇਟ",
    "Official License": "ਸਰਕਾਰੀ ਲਾਇਸੈਂਸ",
    "Verification Letter": "ਤਸਦੀਕ ਪੱਤਰ"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [languageCode, setLanguageCode] = useState('en');

  const currentLanguage = languages.find(l => l.code === languageCode) || languages[0];
  const setLanguage = (code: string) => setLanguageCode(code);

  const t = (key: string) => {
    const langData = translations[languageCode] || translations['en'];
    return langData[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};